Areas:
  Gestao:
    name: Gestão
    subItens:
      Users:
        name: Usuários
        description: Área de controle de Usuários
        icon: fad fa-user
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator]
      Roles:
        name: Funções
        description: Gerenciamento de funções e permissões
        customView: roles
        icon: fad fa-user-shield
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level=Administrator
      Reports:
        name: Relatórios
        description: Visualização de relatórios gerenciais
        icon: fad fa-chart-line
        actions: [Consult, Export]
        showIf: session@level in [Administrator, Manager]

  Financeiro:
    name: Financeiro
    subItens:
      Invoices:
        name: Faturas
        description: Gestão de faturas e pagamentos
        icon: fad fa-file-invoice-dollar
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator, Finance]
      Expenses:
        name: Despesas
        description: Controle de despesas operacionais
        icon: fad fa-money-bill-wave
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator, Finance]
      Budget:
        name: Orçamento
        description: Planejamento e acompanhamento orçamentário
        icon: fad fa-wallet
        actions: [Consult, Update]
        showIf: session@level in [Administrator]

  RecursosHumanos:
    name: Recursos Humanos
    subItens:
      Employees:
        name: Funcionários
        description: Cadastro e gerenciamento de funcionários
        icon: fad fa-users
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator, HR]
      Payroll:
        name: Folha de Pagamento
        description: Processamento da folha de pagamento
        icon: fad fa-file-invoice
        actions: [Consult, Update, Generate]
        showIf: session@level in [HR]
      Recruitment:
        name: Recrutamento
        description: Gestão de processos seletivos
        icon: fad fa-user-plus
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator, HR, Recruiter]

  TI:
    name: TI
    subItens:
      Servers:
        name: Servidores
        description: Monitoramento e configuração de servidores
        icon: fad fa-server
        actions: [Consult, Update, Restart]
        showIf: session@level in [Administrator]
      Network:
        name: Rede
        description: Gerenciamento de dispositivos de rede
        icon: fad fa-network-wired
        actions: [Consult, Update]
        showIf: session@level in [Administrator, IT]
      Support:
        name: Suporte
        description: Atendimento e resolução de tickets de suporte
        icon: fad fa-headset
        actions: [Consult, Update, Close]
        showIf: session@level in [Administrator, IT, Support]
  
  Sistema:
    subItens:
      Profile:
        name: Perfis de Acesso
        description: Área de controle de perfis de acesso
        icon: fad fa-lock
        actions: [Consult, Update, Insert]
        showIf: session@level in [Administrator, Entity]
      Users:
        name: Usuários
        description: Área de gestão de usuários
        icon: fad fa-user-shield
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator, Entity]
      Person:
        name: Operadores
        description: Área de gestão de operadores
        icon: fad fa-user-circle
        actions: [Consult, Update, Insert, Delete]
        showIf: session@level in [Administrator, Entity]

  Notifications:
    subItens:
      Notification:
        name: Notificações
        description: Área de controle das notificações
        icon: fad fa-bell
        actions: [Consult]

