Areas:
  Gestao:
    name: Gestão
    icon: fad fa-tools
    subItens:
      MeasurementUnit:
        name: Unidades de Medida
        description: Gerenciamento das unidades de medida
        icon: fad fa-ruler-triangle
        actions:
          - Consult
          - Insert
          - Delete
          - Edit
      Brand:
        name: Marcas
        description: Gerenciamento das marcas
        icon: fad fa-tags
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
      Ingredient:
        name: Ingredientes
        description: Gerenciamento dos Ingredientes
        icon: fad fa-utensils-alt
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
  Produtos:
    name: Produtos
    icon: fad fa-cauldron
    subItens:
      Recipe:
        name: Receitas
        description: Gestão das receitas do sistema
        icon: fad fa-book-spells
        actions:
          - Consult
          - Insert
          - Delete 
          - Edit
      RecipeUsage:
        name: Uso de Receita
        description: Gestão dos uso de receitas
        icon: fad fa-cauldron
        actions:
          - Consult
          - Insert
          - Delete
          - Edit
  Financeiro:
    name: Financeiro
    icon: fad fa-money-bill-wave
    subItens:
      Purchase:
        name: Compras
        description: Gestão das compras de ingredientes
        icon: fad fa-money-bill-wave
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
  TI:
    name: TI
    icon: fad fa-user-robot
    subItens:
      Servers:
        name: Servidores
        description: Monitoramento e configuração de servidores
        icon: fad fa-server
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
        showIf: session@level in [Administrator]
      Network:
        name: Rede
        description: Gerenciamento de dispositivos de rede
        icon: fad fa-network-wired
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
        showIf: session@level in [Administrator, IT]
      Support:
        name: Suporte
        description: Atendimento e resolução de tickets de suporte
        icon: fad fa-headset
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
        showIf: session@level in [Administrator, IT, Support]
  
  Sistema:
    name: Sistema
    icon: fad fa-galaxy
    subItens:
      Profile:
        name: Perfis de Acesso
        description: Área de controle de perfis de acesso
        icon: fad fa-lock
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
        showIf: session@level in [Administrator, Entity]
      User:
        name: Usuários
        description: Área de gestão de usuários
        icon: fad fa-user-shield
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
        showIf: session@level in [Administrator, Entity]
      Person:
        name: Operadores
        description: Área de gestão de operadores
        icon: fad fa-user-circle
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit
        showIf: session@level in [Administrator, Entity]

  Notifications:
    name: Notificações
    icon: fad fa-bell
    subItens:
      Notification:
        name: Notificações
        description: Área de controle das notificações
        icon: fad fa-bell
        actions: 
          - Consult
          - Insert
          - Delete
          - Edit

